export const BIOTECH_TICKERS = [
  "LLY","JNJ","ABBV","MRK","AMGN","GILD","PFE","BMY","VRTX","REGN",
  "BIIB","ALNY","ARGX","BMRN","IONS","MRNA","BNTX","INCY","JAZZ","EXEL",
  "NBIX","INSM","CYTK","TGTX","ACAD","AXSM","DNLI","SRPT","DXCM","ILMN",
  "AZN","NVO","NVS","GSK","SNY","TMO","ABT","DHR","ISRG","MDT",
  "SYK","BSX","UNH","CVS","HCA","TEVA","FOLD","IOVA","PCVX","RVMD"
] as const;

export type BiotechTicker = typeof BIOTECH_TICKERS[number];

// Map tickers to company/sponsor names for ClinicalTrials.gov
export const TICKER_TO_SPONSOR: Record<string, string> = {
  LLY: "Eli Lilly",
  JNJ: "Johnson & Johnson",
  ABBV: "AbbVie",
  MRK: "Merck",
  AMGN: "Amgen",
  GILD: "Gilead Sciences",
  PFE: "Pfizer",
  BMY: "Bristol-Myers Squibb",
  VRTX: "Vertex Pharmaceuticals",
  REGN: "Regeneron",
  BIIB: "Biogen",
  ALNY: "Alnylam",
  ARGX: "argenx",
  BMRN: "BioMarin",
  IONS: "Ionis Pharmaceuticals",
  MRNA: "Moderna",
  BNTX: "BioNTech",
  INCY: "Incyte",
  JAZZ: "Jazz Pharmaceuticals",
  EXEL: "Exelixis",
  NBIX: "Neurocrine Biosciences",
  INSM: "Insmed",
  CYTK: "Cytokinetics",
  TGTX: "TG Therapeutics",
  ACAD: "Acadia Pharmaceuticals",
  AXSM: "Axsome Therapeutics",
  DNLI: "Denali Therapeutics",
  SRPT: "Sarepta Therapeutics",
  DXCM: "DexCom",
  ILMN: "Illumina",
  AZN: "AstraZeneca",
  NVO: "Novo Nordisk",
  NVS: "Novartis",
  GSK: "GSK",
  SNY: "Sanofi",
  TMO: "Thermo Fisher",
  ABT: "Abbott",
  DHR: "Danaher",
  ISRG: "Intuitive Surgical",
  MDT: "Medtronic",
  SYK: "Stryker",
  BSX: "Boston Scientific",
  UNH: "UnitedHealth",
  CVS: "CVS Health",
  HCA: "HCA Healthcare",
  TEVA: "Teva Pharmaceutical",
  FOLD: "Amicus Therapeutics",
  IOVA: "Iovance Biotherapeutics",
  PCVX: "Vaxcyte",
  RVMD: "Revolution Medicines",
};

export const TICKER_TO_NAME: Record<string, string> = {
  LLY: "Eli Lilly & Co",
  JNJ: "Johnson & Johnson",
  ABBV: "AbbVie Inc",
  MRK: "Merck & Co",
  AMGN: "Amgen Inc",
  GILD: "Gilead Sciences",
  PFE: "Pfizer Inc",
  BMY: "Bristol-Myers Squibb",
  VRTX: "Vertex Pharmaceuticals",
  REGN: "Regeneron Pharmaceuticals",
  BIIB: "Biogen Inc",
  ALNY: "Alnylam Pharmaceuticals",
  ARGX: "argenx SE",
  BMRN: "BioMarin Pharmaceutical",
  IONS: "Ionis Pharmaceuticals",
  MRNA: "Moderna Inc",
  BNTX: "BioNTech SE",
  INCY: "Incyte Corp",
  JAZZ: "Jazz Pharmaceuticals",
  EXEL: "Exelixis Inc",
  NBIX: "Neurocrine Biosciences",
  INSM: "Insmed Inc",
  CYTK: "Cytokinetics Inc",
  TGTX: "TG Therapeutics",
  ACAD: "Acadia Pharmaceuticals",
  AXSM: "Axsome Therapeutics",
  DNLI: "Denali Therapeutics",
  SRPT: "Sarepta Therapeutics",
  DXCM: "DexCom Inc",
  ILMN: "Illumina Inc",
  AZN: "AstraZeneca PLC",
  NVO: "Novo Nordisk A/S",
  NVS: "Novartis AG",
  GSK: "GSK PLC",
  SNY: "Sanofi SA",
  TMO: "Thermo Fisher Scientific",
  ABT: "Abbott Laboratories",
  DHR: "Danaher Corp",
  ISRG: "Intuitive Surgical",
  MDT: "Medtronic PLC",
  SYK: "Stryker Corp",
  BSX: "Boston Scientific",
  UNH: "UnitedHealth Group",
  CVS: "CVS Health Corp",
  HCA: "HCA Healthcare",
  TEVA: "Teva Pharmaceutical",
  FOLD: "Amicus Therapeutics",
  IOVA: "Iovance Biotherapeutics",
  PCVX: "Vaxcyte Inc",
  RVMD: "Revolution Medicines",
};
